#!/bin/bash

# Cloudflare Pages 快速配置脚本
# 使用方法: bash setup-cloudflare-pages.sh

echo "========================================="
echo "  Cloudflare Pages 部署配置助手"
echo "========================================="
echo ""

echo "📋 请按照以下步骤操作："
echo ""

echo "1️⃣ 第一步：登录Cloudflare"
echo "   访问: https://dash.cloudflare.com"
echo "   用户名: snh@263.net"
echo "   密码: sunnianhui@319410"
echo ""

echo "2️⃣ 第二步：创建Pages项目"
echo "   a) 点击左侧菜单 'Workers & Pages'"
echo "   b) 点击 'Create application' → 'Pages'"
echo "   c) 选择 'Connect to Git'"
echo ""

echo "3️⃣ 第三步：连接GitHub"
echo "   a) 点击 'Connect GitHub'"
echo "   b) 授权Cloudflare访问您的GitHub账户"
echo "   c) 选择仓库: benjamin1969/novel-site"
echo "   d) 点击 'Begin setup'"
echo ""

echo "4️⃣ 第四步：配置构建设置"
echo "   ⚙️ 重要配置："
echo "   - Project name: novel-platform"
echo "   - Production branch: main"
echo "   - Framework preset: None"
echo "   - Build command: npm run build"
echo "   - Build output directory: .next/standalone"
echo "   - Root directory: / (保持默认)"
echo ""

echo "5️⃣ 第五步：添加环境变量"
echo "   点击 'Environment variables' → 'Add variable'"
echo "   添加以下变量："
echo ""
echo "   🔐 DATABASE_URL"
echo "   值: postgresql://neondb_owner:npg_Awnt1qIMO4YS@ep-patient-frost-amrgdg0v-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
echo ""
echo "   🔐 JWT_SECRET"
echo "   值: [从您的.env文件复制JWT_SECRET值]"
echo ""
echo "   🔐 NODE_ENV"
echo "   值: production"
echo ""

echo "6️⃣ 第六步：高级设置"
echo "   a) 点击 'Settings' → 'Builds & deployments'"
echo "   b) 确保 Node.js version: 18"
echo "   c) Build caching: Enabled"
echo ""

echo "7️⃣ 第七步：部署"
echo "   a) 点击 'Save and Deploy'"
echo "   b) 等待构建完成（约10-15分钟）"
echo ""

echo "8️⃣ 第八步：验证"
echo "   构建完成后，访问："
echo "   - 默认域名: https://novel-platform.pages.dev"
echo "   - 检查构建日志是否有错误"
echo ""

echo "🎯 自定义域名（可选）"
echo "   1. 点击 'Settings' → 'Custom domains'"
echo "   2. 点击 'Set up a custom domain'"
echo "   3. 输入: dskxx.ccwu.cc"
echo "   4. 按照DNS配置说明操作"
echo ""

echo "========================================="
echo "  快速验证命令"
echo "========================================="
echo ""
echo "# 检查GitHub仓库"
echo "curl -s -o /dev/null -w \"%{http_code}\" https://github.com/benjamin1969/novel-site"
echo ""
echo "# 本地测试构建"
echo "npm run build"
echo ""
echo "# 检查输出目录"
echo "ls -la .next/standalone"
echo ""

echo "========================================="
echo "  故障排除"
echo "========================================="
echo ""
echo "❌ 问题: 构建失败 'next: not found'"
echo "✅ 解决: 确保package.json中有正确的依赖"
echo ""
echo "❌ 问题: 'ENOENT: no such file or directory'"
echo "✅ 解决: 确保输出目录设置为 .next/standalone"
echo ""
echo "❌ 问题: 'DATABASE_URL is not defined'"
echo "✅ 解决: 确保环境变量已正确设置"
echo ""

echo "📞 支持资源"
echo "- Cloudflare文档: https://developers.cloudflare.com/pages/"
echo "- Next.js部署指南: https://nextjs.org/docs/deployment"
echo "- 构建日志: 在Cloudflare Pages项目中查看"
echo ""

echo "🎉 完成！您的网站将在以下地址可用："
echo "   https://novel-platform.pages.dev"
echo "   或"
echo "   https://dskxx.ccwu.cc (配置自定义域名后)"
echo ""

read -p "按Enter键继续查看详细指南，或Ctrl+C退出..."